# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				camel = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				mooshroom = true
				llama_spit = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				end_crystal = true
				ender_pearl = true
				zombie = true
				item_display = true
				guardian = true
				fireball = true
				illusioner = true
				wither_skull = true
				eye_of_ender = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				block_display = true
				elder_guardian = true
				chest_boat = true
				small_fireball = true
				boat = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				vex = true
				wither_skeleton = true
				wandering_trader = true
				salmon = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				warden = true
				glow_squid = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.betterarcheology]
				bombentity = true

			[light_sources.settings.entities.endermanoverhaul]
				flower_fields_enderman = true
				coral_enderman = true
				ender_bullet = true
				windswept_hills_enderman = true
				icy_pearl = true
				summoner_pearl = true
				nether_wastes_enderman = true
				soul_pearl = true
				mushroom_fields_enderman = true
				snowy_enderman = true
				soulsand_valley_enderman = true
				axolotl_pet_enderman = true
				hammerhead_pet_enderman = true
				savanna_enderman = true
				ice_spikes_enderman = true
				desert_enderman = true
				spirit = true
				ancient_pearl = true
				end_enderman = true
				corrupted_pearl = true
				bubble_pearl = true
				crimson_forest_enderman = true
				warped_pearl = true
				cave_enderman = true
				dark_oak_enderman = true
				crimson_pearl = true
				end_islands_enderman = true
				scarab = true
				swamp_enderman = true
				badlands_enderman = true
				warped_forest_enderman = true
				pet_enderman = true

			[light_sources.settings.entities.underground_jungle]
				mossy_skeleton = true
				jungle_zombie = true

			[light_sources.settings.entities.levelz]
				level_experience_orb = true

			[light_sources.settings.entities.connectiblechains]
				chain_knot = true
				chain_collision = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				sludge = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				chest_boat = true
				angler_fish = true
				boat = true
				sculk_snapper = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.illagerinvasion]
				skull_bolt = true
				sorcerer = true
				alchemist = true
				surrendered = true
				basher = true
				necromancer = true
				firecaller = true
				invoker = true
				marauder = true
				invoker_fangs = true
				flying_magma = true
				hatchet = true
				archivist = true
				provoker = true
				inquisitor = true

			[light_sources.settings.entities.galosphere]
				sparkle = true
				spectator_vision = true
				glow_flare = true
				spectre_flare = true
				spectre = true
				berserker = true
				pink_salt_pillar = true
				preserved = true
				silver_bomb = true
				pink_salt_shard = true
				specterpillar = true

			[light_sources.settings.entities.snowrealmagic]
				snow = true

			[light_sources.settings.entities.smallships]
				galley = true
				brigg = true
				drakkar = true
				cog = true
				cannon_ball = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				jungle_skeleton = true
				skull = true
				naga = true

			[light_sources.settings.entities.obscure_api]
				texture_fx = true

			[light_sources.settings.entities.adventurez]
				deer = true
				skeleton_vanguard = true
				thrown_rock = true
				desert_rhino = true
				blaze_guardian = true
				ender_whale = true
				piglin_beast = true
				shaman = true
				dragon = true
				iguana = true
				amethyst_golem = true
				soul_reaper = true
				red_fungus = true
				void_cloud = true
				summoner = true
				void_bullet = true
				orc = true
				the_eye = true
				fire_breath = true
				necromancer = true
				void_fragment = true
				blaze_guardian_shield = true
				brown_fungus = true
				blackstone_golem = true
				nightmare = true
				mini_blackstone_golem = true
				mammoth = true
				void_shade = true
				tiny_eye = true
				enderwarthog = true
				wither_puppet = true
				void_shadow = true
				amethyst_shard = true
				gilded_blackstone_shard = true

			[light_sources.settings.entities.bclib]
				chair = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				cubozoa = true
				shadow_walker = true
				end_slime = true
				silk_moth = true
				end_fish = true

			[light_sources.settings.entities.dungeonnowloading]
				ballista_arrow = true
				fairkeeper_ouros = true
				spawner_carrier = true
				fairkeeper_boros = true
				hollow = true
				chaos_spawner_projectile = true
				copper_creep = true
				special_item_entity = true
				fairkeeper_boros_part = true
				whimper = true
				vertex_arrow_projectile = true
				borus_arrow = true
				ballista_golem = true
				chaos_spawner = true
				great_experience_bottle = true
				vertex_pillar_projectile = true
				vertex_orb_projectile = true
				fairkeeper_ouros_part = true
				fairkeeper_serpent_caller = true
				vertex_domain_projectile = true
				scuttle = true
				sealed_chaos = true
				flame_projectile = true
				repulsor = true

			[light_sources.settings.entities.aquamirae]
				captain_cornelia = true
				tortured_soul = true
				maw = true
				anglerfish = true
				golden_moth = true
				pillagers_patrol = true
				maze_rose = true
				maze_mother = true
				eel = true
				poisoned_chakra = true
				spinefish = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.travelersbackpack]
				backpack = true

[debug]
	active_dynamic_lighting_cells = false
	cell_display_radius = 0
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false
	light_level_radius = 0
